### ISSUE TITLE
issue for testing c4gt #2

### ISSUE THREAD

**Issue by jaanbaaz** [jaanbaaz/c4gt-server-webhook#10]
## Description

-   In quiz assessment we can navigate questions through questionPalette and see instructions from the palette itself.
-   In omr-assessment there is no need for palette but it is required to show instructions.
- This has been added again

## Goals
- [ ]  Instruction Page for OMR format
- [ ] -   Palette for OMR format

### Expected Outcome

Instruction page and palette for OMR format are available on frontend.

### Implementation Details

Read through  `OMRModal.vue`,  `Player.vue`  components.

### Product Name

Quiz Frontend

### Organisation Name

C4GT

### Domain

Education

### Tech Skills Needed

Vue.js, HTML, CSS, JavaScript

### Mentor(s)

[@suryabulusu](https://github.com/suryabulusu)

### Advisor

[@suryabulusu](https://github.com/suryabulusu)

### Designer

[@suryabulusu](https://github.com/suryabulusu)

### Contributor

[@suryabulusu](https://github.com/suryabulusu)

### Complexity

Medium

### Category

Frontend

**Comment by jaanbaaz** [comment]
commenting to test it out

**Comment by jaanbaaz** [comment]
test comment

**Comment by divineshiva003** [comment]
Hii @jaanbaaz 
Please assign this task to me
It will help me boost my experience

**Comment by jaanbaaz** [comment]
adding comments here

**Comment by jaanbaaz** [comment]
adding comments again

**Comment by jaanbaaz** [comment]
added a new comment
